CREATE USER C##WEBFRONT IDENTIFIED BY WEBFRONT;

GRANT CREATE session to C##WEBFRONT;

-- 일반 사용자 역할 수행
GRANT CONNECT, RESOURCE TO C##WEBFRONT;

ALTER USER C##WEBFRONT  
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS;